fix ODR violation of global LLVMZeroValueCTX and LLVMZeroValueMod
secure-software-engineering/phasar pull request #423
Opened 2021-09-27 10:57 UTC by MMory

2021-09-28 09:28 UTC, vulder requested changes

2021-09-28 09:28 UTC, vulder commented on include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/LLVMZeroValue.h
> +inline const std::unique_ptr<llvm::Module>
```suggestion
static inline const std::unique_ptr<llvm::Module>
```

2021-09-28 09:46 UTC, MMory commented on include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/LLVMZeroValue.h
> +inline const std::unique_ptr<llvm::LLVMContext>
nope. by doing so we have one instance per compiled cpp file, which is wrong.

2021-09-28 09:48 UTC, vulder commented on include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/LLVMZeroValue.h
> +inline const std::unique_ptr<llvm::LLVMContext>
but with the inline all these instances are collapsed during linking, so the final binary only has one instance

2021-09-28 09:52 UTC, MMory commented on include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/LLVMZeroValue.h
> +inline const std::unique_ptr<llvm::LLVMContext>
they are not. This is what I expected too, but in the debugger I could see there is one instance per compiled file. The collapsing takes place for members iirc, but those are no members.

2021-09-28 09:58 UTC, vulder commented on include/phasar/PhasarLLVM/DataFlowSolver/IfdsIde/LLVMZeroValue.h
> +inline const std::unique_ptr<llvm::LLVMContext>
ah, yeah the inline static only is relevant for static members variables, for globals the inline is enough

2021-09-28 09:58 UTC, vulder approved these changes

2021-10-01 08:54 UTC, pdschubert approved these changes

2021-10-01 08:54 UTC, merged