clang-tidy: Fixes in passes
secure-software-engineering/phasar pull request #477
Opened 2022-01-10 16:05 UTC by MMory

2022-01-10 20:11 UTC, vulder requested changes

2022-01-10 20:11 UTC, vulder commented on include/phasar/PhasarLLVM/Passes/ExampleModulePass.h
> +  static llvm::AnalysisKey Key; // NOLINT
Why does this static variable need a //NOLINT?

2022-01-10 20:11 UTC, vulder commented on include/phasar/PhasarLLVM/Passes/GeneralStatisticsAnalysis.h
> +  static llvm::AnalysisKey Key; // NOLINT
same here

2022-01-10 20:11 UTC, vulder commented on include/phasar/PhasarPass/Options.h
> +extern llvm::cl::OptionCategory PhASARCategory; // NOLINT
Are externs not allowed? If this should be so, maybe we should consider removing the clang-tidy rule?

2022-01-10 20:11 UTC, vulder commented on lib/PhasarPass/RegisterPasses.cpp
> +    SetPrintEdgeRecorder("printedgerec", // NOLINT
What rule is triggering here? This one works without errors 4 me.

2022-01-11 15:30 UTC, pdschubert approved these changes

2022-01-11 15:35 UTC, merged