Filtered AliasSet
secure-software-engineering/phasar pull request #723
Opened 2024-05-10 12:31 UTC by fabianbs96

The `LLVMAliasSet` contains a lot of spurious aliases due to its context insensitivity and its almost not present field-sensitivity.
Hence, the client analyses based on this alias information produces many false positives and need to propagate many more facts than necessary, resulting in a severe performance hit.

Therefore, some analyses in phasar, such as the `IFDSTaintAnalysis` and `IDEExtendedTaintAnalysis`, filter the alias sets on-the-fly to achieve better results.

This PR provides a wrapper `FilteredLLVMAliasSet` around the `LLVMAliasSet` that abstracts and caches the filtering.

2024-05-12 08:07 UTC, vulder requested changes
Where do you implement the caching (I might have missed it :laughing: ) and how exactly do you ensure that the cache is a) not to big and b) how do you do cache invalidation.

2024-05-12 08:07 UTC, vulder commented on include/phasar/PhasarLLVM/Pointer/FilteredLLVMAliasSet.h
> +  using traits_t = AliasInfoTraits<FilteredLLVMAliasSet>;
you might call it `alias_traits_t` so it easier to see what kind of traits one accesses in the following code.

2024-05-12 08:07 UTC, vulder commented on include/phasar/PhasarLLVM/Pointer/FilteredLLVMAliasSet.h
> +
```suggestion
```

2024-05-12 08:07 UTC, vulder commented on include/phasar/PhasarLLVM/Pointer/FilteredLLVMAliasSet.h
> +  FilteredLLVMAliasSet &operator=(FilteredLLVMAliasSet &&) = delete;
```suggestion
  FilteredLLVMAliasSet &operator=(FilteredLLVMAliasSet &&) noexcept = delete;
```

2024-05-12 08:07 UTC, vulder commented on include/phasar/PhasarLLVM/Pointer/FilteredLLVMAliasSet.h
> +  MaybeUniquePtr<LLVMAliasSet, true> AS;
```suggestion
  MaybeUniquePtr<LLVMAliasSet, true /*requiresAlignment*/> AS;
```

2024-05-12 08:07 UTC, vulder commented on lib/PhasarLLVM/Pointer/FilteredLLVMAliasSet.cpp
> +[[nodiscard]] static bool isConstantGlob(const llvm::GlobalValue *GlobV) {
```suggestion
[[nodiscard]] static bool isConstantGlobalValue(const llvm::GlobalValue *GlobV) {
```
I find Glob not super easy to understand. I immediatly mixed it with shell globbing.

2024-05-12 08:07 UTC, vulder commented on lib/PhasarLLVM/Pointer/FilteredLLVMAliasSet.cpp
> +  }
Why do you need a dyn_cast here? `GlobV` is already the type you want.

2024-05-12 08:07 UTC, vulder commented on lib/PhasarLLVM/Pointer/FilteredLLVMAliasSet.cpp
> +        llvm::isa<llvm::ConstantData>(Alias)) {
```suggestion
    if (llvm::isa<llvm::ConstantExpr, llvm::ConstantData>(Alias)) {
```

2024-05-12 12:59 UTC, fabianbs96 commented on include/phasar/PhasarLLVM/Pointer/FilteredLLVMAliasSet.h
> +  FilteredLLVMAliasSet &operator=(FilteredLLVMAliasSet &&) = delete;
Does it make a difference to declare a deleted function `noexcept`?

2024-05-12 12:59 UTC, fabianbs96 commented on include/phasar/PhasarLLVM/Pointer/FilteredLLVMAliasSet.h
> +  MaybeUniquePtr<LLVMAliasSet, true> AS;
done

2024-05-12 12:59 UTC, fabianbs96 commented on lib/PhasarLLVM/Pointer/FilteredLLVMAliasSet.cpp
> +[[nodiscard]] static bool isConstantGlob(const llvm::GlobalValue *GlobV) {
done

2024-05-12 13:00 UTC, fabianbs96 commented on lib/PhasarLLVM/Pointer/FilteredLLVMAliasSet.cpp
> +  }
`GlobV` here is a `GlobalValue`, but I need it to be a `GlobalVariable` in order to call `isConstant()`.

2024-05-12 13:00 UTC, fabianbs96 commented on lib/PhasarLLVM/Pointer/FilteredLLVMAliasSet.cpp
> +        llvm::isa<llvm::ConstantData>(Alias)) {
Nice, thanks; I didn't know about that!

2024-05-12 13:06 UTC, fabianbs96 commented
Hi @vulder, thanks for your comments.
To answer your questions:

> Where do you implement the caching (I might have missed it 😆 )

The caching is implemented in `getAliasSet()`, but now I have also implemented it for `getReachableAllocationSites()`

> and how exactly do you ensure that the cache is a) not to big and b) how do you do cache invalidation.

Currently, I have not implemented cache invalidation and just keep the cache growing. In my tests (on some coreutils), it has not been any problem. Also, for IFDS and IDE analyses, it is hard to predict, when an alias set is never used again. 

One could implement some ref-counting or least-recently-used strategy, but I havent' implemented it (yet?)

2024-05-13 17:26 UTC, vulder commented on lib/PhasarLLVM/Pointer/FilteredLLVMAliasSet.cpp
> +  }
Ah, sry I miss read that

2024-05-13 17:27 UTC, vulder commented on include/phasar/PhasarLLVM/Pointer/FilteredLLVMAliasSet.h
> +  FilteredLLVMAliasSet &operator=(FilteredLLVMAliasSet &&) = delete;
Yes, a) you do the same thing for the move ctor and b) with noexcept is the correct signature of the function, so deleting it like this is the proper way

2024-05-13 20:26 UTC, vulder commented
> Hi @vulder, thanks for your comments. To answer your questions:
> 
> > Where do you implement the caching (I might have missed it 😆 )
> 
> The caching is implemented in `getAliasSet()`, but now I have also implemented it for `getReachableAllocationSites()`
> 
> > and how exactly do you ensure that the cache is a) not to big and b) how do you do cache invalidation.
> 
> Currently, I have not implemented cache invalidation and just keep the cache growing. In my tests (on some coreutils), it has not been any problem. Also, for IFDS and IDE analyses, it is hard to predict, when an alias set is never used again.
> 
> One could implement some ref-counting or least-recently-used strategy, but I havent' implemented it (yet?)

Ok, just keep in mind invalidation could also be interesting when the cache grows to big. So, even when a set would be needed again afterwards it would be useful to remove it from the cache to reduce the memory footprint.

2024-05-16 12:03 UTC, MMory approved these changes

2024-05-16 12:03 UTC, MMory commented on lib/PhasarLLVM/DataFlow/IfdsIde/Problems/IFDSTaintAnalysis.cpp
>      container_type &Facts, const llvm::Instruction *Context) const {
The name Context is misleading/confusing me, context rather resembles a calling context, while here it is used as the statement at which the aliases are requested, in the sense of flow-sensitivity

2025-02-19 13:28 UTC, sritejakv approved these changes

2025-02-22 15:27 UTC, merged